#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh


# I have a dual screen so i split my windows between them
# If connected connect to share 5 to DP-1
# The default is eDP-1
#
# To find which screen cards to use run xrandr -q | grep "connected" 
~/confs/dots/bspwm/dual_monitor.sh

# bspc monitor eDP-1 -d 1 2 3 4 5
# bspc monitor DP-1 -d 6 7 8 9 0


bspc config border_width         2 
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Albert border=off
bspc rule -a "albert Albert" border=off

albert &
