[package]
name = "startswith"
version = "0.1.0"
authors = ["Yağız can Değirmenci <yagizcanilbey1903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
